#!/usr/bin/env bash
# Run this on the Digital Ocean droplet as root:
#   ssh root@147.182.191.226 'bash -s' < server-setup.sh

set -euo pipefail

DOMAIN="freestate.party"
WEBROOT="/var/www/$DOMAIN"

echo "==> Creating web root"
mkdir -p "$WEBROOT"

echo "==> Creating empty known-routes.conf (will be populated on first deploy)"
touch "$WEBROOT/known-routes.conf"

echo "==> Installing certbot"
apt-get update -qq
apt-get install -y -qq certbot python3-certbot-nginx

echo "==> Getting SSL certificate (certonly — we manage nginx config ourselves)"
certbot certonly --nginx -d freestate.party -d www.freestate.party \
    --non-interactive --agree-tos --email admin@freestate.party

echo "==> Writing nginx config"
cat > /etc/nginx/sites-available/$DOMAIN <<'NGINX'
# HTTP → HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name freestate.party www.freestate.party;
    return 301 https://$host$request_uri;
}

# HTTPS server
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name freestate.party www.freestate.party;

    ssl_certificate /etc/letsencrypt/live/freestate.party/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/freestate.party/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/freestate.party;

    # Legacy URL redirect
    rewrite ^/saturdays/?$ /saturday/ permanent;

    # Marketing pages (auto-generated by build.py)
    include /var/www/freestate.party/known-routes.conf;

    # Next.js assets → proxy to app (^~ beats the static asset regex)
    location ^~ /_next/ {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Marketing static assets from disk
    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff2?|ttf|mp4|webm)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    # Everything else → Next.js app on same server
    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_http_version 1.1;
    }

    # Marketing 404 (only for nginx-generated 404s, not app 404s)
    error_page 404 /404.html;
    location = /404.html { internal; }
}
NGINX

echo "==> Enabling site"
ln -sf /etc/nginx/sites-available/$DOMAIN /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

echo "==> Testing nginx config"
nginx -t

echo "==> Reloading nginx"
systemctl reload nginx

echo "==> Done! Site is live at https://freestate.party"
